config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

    resources :users do
    member do
      get :following, :followers
    end
  end

  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  root 'sessions#root'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<% if logged_in? %> 
				  <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					  <%= current_user.name %> <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
					  <li><%= link_to "Profile", current_user %></li>
					  <li class="divider"></li>
					  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
					</ul>
				  </li>
				<% else %>
				  <li><%= link_to "Log in", sessions_new_path %></li>
				  <li><%= link_to "Sign up",   new_user_path %></li>
				  <li><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangXaHoi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
	
	<div class="container">
		<%= yield %>
	</div>
  </body>
</html>